#!/usr/bin/env bash

connector_name="$1"

[ -z $connector_name ] && {
  echo "connector name must be provided" >&2
  exit 1
}

curl -X DELETE localhost:8080/connectors/$connector_name -H "Content-Type: application/json"
