#!/usr/bin/env bash

unzip /app/jcustenborder-kafka-connect-redis-0.0.2-SNAPSHOT.zip -d /app/kafka-connect-redis
ln -s /app/kafka-connect-redis/jcustenborder-kafka-connect-redis-0.0.2-SNAPSHOT/lib /app/.apt/usr/share/java/kafka-connect-redis 
